### ISSUE TITLE
usbip: error: vhci driver is not loaded

### ISSUE THREAD

**Issue by d805302023** [bulwarkid/virtual-fido#29]
env -> win10 host，win10 vm
after running "go run ./cmd/demo start" and then an error was reported

[LOG] Log Level Set: 2
usbip: error: vhci driver is not loaded
panic: ERROR: Could not read data - read tcp 127.0.0.1:3240->127.0.0.1:59287: wsarecv: An existing connection was forcibly closed by the remote host.

goroutine 6 [running]:
github.com/bulwarkid/virtual-fido/util.CheckErr(...)
        E:/repo/virtual-fido/util/util.go:24
github.com/bulwarkid/virtual-fido/util.ReadBE[...]({0x154ed4c4ff8?, 0xc0000a2010?})
        E:/repo/virtual-fido/util/util.go:44 +0x12d
github.com/bulwarkid/virtual-fido/usbip.(*USBIPServer).handleCommands(0x685b20?, 0xc000086050)
        E:/repo/virtual-fido/usbip/usbip_server.go:68 +0x65
github.com/bulwarkid/virtual-fido/usbip.(*USBIPServer).handleConnection(0xc000098000, 0xc000086050)
        E:/repo/virtual-fido/usbip/usbip_server.go:60 +0x49d
github.com/bulwarkid/virtual-fido/usbip.(*USBIPServer).Start(0x5a72c0?)
        E:/repo/virtual-fido/usbip/usbip_server.go:39 +0x12e
github.com/bulwarkid/virtual-fido.startClient({0x689ad8?, 0xc00007abe0})
        E:/repo/virtual-fido/client_usbip.go:18 +0x3b6
github.com/bulwarkid/virtual-fido.Start(...)
        E:/repo/virtual-fido/virtual_fido.go:18
main.runServer.func1()
        E:/repo/virtual-fido/cmd/demo/server.go:78 +0x25
created by main.runServer in goroutine 1
        E:/repo/virtual-fido/cmd/demo/server.go:77 +0x93
exit status 2

**Comment by alexeygritsenko** [comment]
See [2](https://github.com/bulwarkid/virtual-fido/issues/12)
