### ISSUE TITLE
crash with "panic: Invalid USB Interface bRequest: 9" when faced with linux hidraw sample code

### ISSUE THREAD

**Issue by nabijaczleweli** [bulwarkid/virtual-fido#32]
With Linux 6.8 `samples/hidraw/hid-example.c`, I get
```
$ sudo ./demo start
[LOG] Log Level Set: 2
panic: Invalid USB Interface bRequest: 9

goroutine 9 [running]:
github.com/bulwarkid/virtual-fido/usbip.(*USBDeviceImpl).handleInterfaceRequest(0xc00009a280?, {0x21, 0x9, 0x309, 0x0, 0x4}, {0xc00221e21c?, 0xc0001a3420?, 0x5798dd?})
        /home/nabijaczleweli/uwu/virtual-fido/usbip/usb_device.go:264 +0x359
github.com/bulwarkid/virtual-fido/usbip.(*USBDeviceImpl).handleControlMessage(0xc00009a280?, {0x21, 0x9, 0x309, 0x0, 0x4}, {0xc00221e21c, 0x4, 0x4})
        /home/nabijaczleweli/uwu/virtual-fido/usbip/usb_device.go:276 +0x145
github.com/bulwarkid/virtual-fido/usbip.(*USBDeviceImpl).handleMessage(0xc000016860, 0x373, 0xc002240000, 0x0, {0x21, 0x9, 0x309, 0x0, 0x4}, {0xc00221e21c, ...})
        /home/nabijaczleweli/uwu/virtual-fido/usbip/usb_device.go:305 +0x205
github.com/bulwarkid/virtual-fido/usbip.(*USBIPServer).handleCommandSubmit(0xc0000124b0, 0xc00007acd0, {0x1, 0x373, 0x20002, 0x0, 0x0})
        /home/nabijaczleweli/uwu/virtual-fido/usbip/usbip_server.go:115 +0x31a
github.com/bulwarkid/virtual-fido/usbip.(*USBIPServer).handleCommands(0x7a08a0?, 0xc00007acd0)
        /home/nabijaczleweli/uwu/virtual-fido/usbip/usbip_server.go:71 +0x165
github.com/bulwarkid/virtual-fido/usbip.(*USBIPServer).handleConnection(0xc0000124b0, 0xc00007acd0)
        /home/nabijaczleweli/uwu/virtual-fido/usbip/usbip_server.go:60 +0x33a
github.com/bulwarkid/virtual-fido/usbip.(*USBIPServer).Start(0x6cdb40?)
        /home/nabijaczleweli/uwu/virtual-fido/usbip/usbip_server.go:39 +0x138
github.com/bulwarkid/virtual-fido.startClient({0x7a4738?, 0xc000000be0})
        /home/nabijaczleweli/uwu/virtual-fido/client_usbip.go:18 +0x3b0
github.com/bulwarkid/virtual-fido.Start(...)
        /home/nabijaczleweli/uwu/virtual-fido/virtual_fido.go:18
main.runServer.func1()
        /home/nabijaczleweli/uwu/virtual-fido/cmd/demo/server.go:78 +0x2b
created by main.runServer
        /home/nabijaczleweli/uwu/virtual-fido/cmd/demo/server.go:77 +0xa5
```
corresponding to
```
$ sudo strace -o ss ./hid-example /dev/hidraw1
Report Descriptor Size: 30
Report Descriptor:
6 d0 f1 9 1 a1 1 9 20 14 25 ff 75 8 95 40 81 2 9 21 14 25 ff 75 8 95 40 91 2 c0

Raw Name: No Company Virtual FIDO
Raw Phys: usb-vhci_hcd.0-1/input0
Raw Info:
        bustype: 3 (USB)
        vendor: 0x0000
        product: 0x0000
HIDIOCSFEATURE: Connection timed out
HIDIOCGFEATURE: No such device
Error: 19
write: No such device
read: Input/output error
```
and
```
$ cat ss
execve("./hid-example", ["./hid-example", "/dev/hidraw1"], 0x7fff00acf8f8 /* 15 vars */) = 0
brk(NULL)                               = 0x556dd50d6000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1a7c453000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=84206, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 84206, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f1a7c43e000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220s\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1922136, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1970000, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1a7c25d000
mmap(0x7f1a7c283000, 1396736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f1a7c283000
mmap(0x7f1a7c3d8000, 339968, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17b000) = 0x7f1a7c3d8000
mmap(0x7f1a7c42b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ce000) = 0x7f1a7c42b000
mmap(0x7f1a7c431000, 53072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1a7c431000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1a7c25a000
arch_prctl(ARCH_SET_FS, 0x7f1a7c25a740) = 0
set_tid_address(0x7f1a7c25aa10)         = 3544323
set_robust_list(0x7f1a7c25aa20, 24)     = 0
rseq(0x7f1a7c25b060, 0x20, 0, 0x53053053) = 0
mprotect(0x7f1a7c42b000, 16384, PROT_READ) = 0
mprotect(0x556dd398d000, 4096, PROT_READ) = 0
mprotect(0x7f1a7c485000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f1a7c43e000, 84206)           = 0
openat(AT_FDCWD, "/dev/hidraw1", O_RDWR|O_NONBLOCK) = 3
ioctl(3, HIDIOCGRDESCSIZE or HIDIOCGVERSION, 0x7ffd6595bdb0) = 0
newfstatat(1, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x8), ...}, AT_EMPTY_PATH) = 0
getrandom("\x72\xd1\xb8\x1e\xb8\xca\x1c\xfc", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x556dd50d6000
brk(0x556dd50f7000)                     = 0x556dd50f7000
write(1, "Report Descriptor Size: 30\n", 27) = 27
ioctl(3, HIDIOCGRDESC, 0x7ffd6595acac)  = 0
write(1, "Report Descriptor:\n", 19)    = 19
write(1, "6 d0 f1 9 1 a1 1 9 20 14 25 ff 7"..., 81) = 81
write(1, "\n", 1)                       = 1
ioctl(3, HIDIOCGRAWNAME(256), 0x7ffd6595bcb0) = 24
write(1, "Raw Name: No Company Virtual FID"..., 34) = 34
ioctl(3, HIDIOCGRAWPHYS(256), 0x7ffd6595bcb0) = 24
write(1, "Raw Phys: usb-vhci_hcd.0-1/input"..., 34) = 34
ioctl(3, HIDIOCGRAWINFO, 0x7ffd6595aca4) = 0
write(1, "Raw Info:\n", 10)             = 10
write(1, "\tbustype: 3 (USB)\n", 18)    = 18
write(1, "\tvendor: 0x0000\n", 16)      = 16
write(1, "\tproduct: 0x0000\n", 17)     = 17
ioctl(3, HIDIOCSFEATURE(4), 0x7ffd6595bcb0) = -1 ETIMEDOUT (Connection timed out)
dup(2)                                  = 4
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
newfstatat(4, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x8), ...}, AT_EMPTY_PATH) = 0
write(4, "HIDIOCSFEATURE: Connection timed"..., 37) = 37
close(4)                                = 0
ioctl(3, HIDIOCGFEATURE(256), 0x7ffd6595bcb0) = -1 ENODEV (No such device)
dup(2)                                  = 4
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
newfstatat(4, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x8), ...}, AT_EMPTY_PATH) = 0
write(4, "HIDIOCGFEATURE: No such device\n", 31) = 31
close(4)                                = 0
write(3, "\1w", 2)                      = -1 ENODEV (No such device)
write(1, "Error: 19\n", 10)             = 10
dup(2)                                  = 4
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
newfstatat(4, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x8), ...}, AT_EMPTY_PATH) = 0
write(4, "write: No such device\n", 22) = 22
close(4)                                = 0
read(3, 0x7ffd6595bcb0, 16)             = -1 EIO (Input/output error)
dup(2)                                  = 4
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
newfstatat(4, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x8), ...}, AT_EMPTY_PATH) = 0
write(4, "read: Input/output error\n", 25) = 25
close(4)                                = 0
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by nabijaczleweli** [comment]
This expectedly matches
```
113     /* Set Feature */
114     buf[0] = 0x9; /* Report Number */
115     buf[1] = 0xff;
116     buf[2] = 0xff;
117     buf[3] = 0xff;
118     res = ioctl(fd, HIDIOCSFEATURE(4), buf);
119     if (res < 0)
120         perror("HIDIOCSFEATURE");
121     else
122         printf("ioctl HIDIOCSFEATURE returned: %d\n", res);
```

**Comment by cmdli** [comment]
What hidraw code is this? This request is a SET_REPORT, which isn't the usual way that FIDO devices communicate. What is the expected behavior here?

**Comment by nabijaczleweli** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/samples/hidraw/hid-example.c?id=v6.6

It's entirely possible this is just Not Supposed To Work anyway. Indeed, doing this to my Somu yields
```
Report Descriptor Size: 34
Report Descriptor:
6 d0 f1 9 1 a1 1 9 20 15 0 26 ff 0 75 8 95 40 81 2 9 21 15 0 26 ff 0 75 8 95 40 91 2 c0

Raw Name: SoloKeys Solo 3.1.2
Raw Phys: usb-vhci_hcd.0-2/input0
Raw Info:
        bustype: 3 (USB)
        vendor: 0x0483
        product: 0xa2ca
HIDIOCSFEATURE: Broken pipe
HIDIOCGFEATURE: Broken pipe
write() wrote 2 bytes
read: Resource temporarily unavailable
```
so it's emulating it relatively sensibly :ssh:
